project:
  type: manuscript

manuscript:
  article: paper2.qmd 
  meca-bundle: "manuscript-meca.zip"
  code-links:
     - text: Github repository
       icon: filetype-html
       href: https://github.com/jriveraespejo/paper2_manuscript.git
     - text: CJ figures
       icon: file-code-fill
       href: code/CJfig.R
     - text: CJ model
       icon: file-code-fill
       href: code/CJmod_add.R
  #   - text: Submission Manuscript
  #     icon: filetype-pdf
  #     href: manual_renderization/index.pdfutations using inlin
  
    
execute:
  freeze: auto
  cache: true
  # eval: true
  echo: false
  # output: true
  # include: true
  warning: false
  error: false
  message: false

format:
  html:
    notebook-links: global
    lightbox: true
    citation: true
        #type: article-journal
        #container-title: "Psychometrika"
        #doi: ""
        #url: https://example.com/summarizing-output
    comments:
      hypothesis: true
    google-scholar: true
    licence: 'CC BY-SA'
    toc: true
    toc-title: 'Table of Contents'
    toc-location: left
    fontsize: 12pt
    number-sections: true
    code-fold: true
    code-summary: "code"
    code-overflow: scroll
    #code-annotations: hover
    #code-line-numbers: false
    tbl-cap-location: top
    fig-cap-location: top
    default image extension: png
  #docx: default
  #jats: default
  elsevier-pdf:
    keep-tex: true
    journal:
      name: Psychometrika
      formatting: review
      model: 1p
      cite-style: authoryear

