project:
  type: manuscript

manuscript:
  article: index.qmd
  notebooks:
    - notebook: notebooks/graphviz_figures.qmd
      title: Graphviz figures
      download-url: notebooks/graphviz_figures.qmd
    - notebook: notebooks/data_simulation.qmd
      title: Data Simulation
      download-url: notebooks/data_simulation.qmd
  #resources:
  #  - data/replication_seeds.rds
  meca-bundle: "manuscript-meca.zip"
  
execute:
  freeze: auto

format:
  html:
    google-scholar: true
    licence: 'CC BY-SA'
    comments:
      hypothesis: true
    cite-method: citeproc
    # csl: apa.csl
    keep-tex: true
    embed-resources: true
    # link-external-icon: true
    # link-external-newwindow: true
    page-layout: article
    # theme: default
    fontsize: 11pt
    smooth-scroll: true
    toc: true
    toc-depth: 3
    toc-expand: 1
    toc-title: 'Table of Contents'
    toc-location: left
    number-sections: true
    # number-depth: 3
    anchor-sections: true
    html-math-method: katex
    citations-hover: true
    footnotes-hover: true
    reference-location: document
    code-fold: true
    code-summary: "Code"
    code-overflow: scroll
    code-tools: true
    code-annotations: hover
    code-line-numbers: false
    code-copy: true
    tbl-cap-location: top
    fig-cap-location: top
  docx: default
  jats: default
  jasa-pdf: default



