project:
  type: manuscript

manuscript:
  article: index.qmd
  notebooks:
    - notebook: notebooks/data_simulation.qmd
      title: Data Simulation
      download-url: notebooks/data_simulation.qmd
  #resources:
  #  - data/replication_seeds.rds
  meca-bundle: "manuscript-meca.zip"
  
execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  jasa-pdf: default



