---
title: Graphviz figures
bibliography: ../references.bib
author: Jose Manuel Rivera Espejo
---

## The Identification-Estimation flowchart

The Identification-Estimation flowchart [@McElreath_2020; @Neal_2020] defines the specific terminology for the study, as well as it provides the steps to follow in order to test the reliability of the DCJ method. Initially, it defines the different targets of inference (i.e., the *estimands*), which form the basis for evaluating the reliability of the DCJ method. The targets are articulated through three research questions. Subsequently, the research constructs a *scientific model* for the DCJ procedure, elucidating the causal assumptions and mechanisms underlying the system, aiding in drawing inferences about causal relationships from DCJ data. Next, the study translates the scientific model into a probabilistic statistical model (i.e., an *estimator*) to derive a *statistical estimand* for the various inference targets. Bayesian statistical methods offer an intuitive approach for the task. Finally, employing multiple simulated datasets for different combinations of the relevant assessment factors, the study generates multiple *estimates* for the statistical estimands. Notably, the statistical estimands in simulated data are known, enabling the study to assess the reliability of DCJ by evaluating the *proximity* of these estimands to the generated estimates, resembling a power analysis. 

```{dot}
//| echo: true
//| label: fig-IEflowchart_Appendix
//| fig-cap: "Identification-Estimation flowchart. Extracted from @Neal_2020 [pp. 32]"
//| fig-height: 4
//| fig-width: 4

digraph mrdag {

  graph [rankdir=TB, layout=neato]

  node [shape=box, height=0.3, width=0.3]
  CE [label="(Causal) Estimand", pos="0,1!"]
  SM [label="Scientific model", pos="2,1!"]
  SE [label="Statistical estimand", pos="0,0!"]
  D [label="Data", pos="2,0!"]
  ES [label="Estimate", pos="0,-1!"]
  
  node [shape=plaintext, height=0.3, width=0.3]
  IT [label="Identification", pos="0.6,0.7!"]
  ET [label="Estimation", pos="0.5,-0.3!"]

  {CE SM} -> SE
  {SE D} -> ES
  
}

```


## A scientific model for the DCJ procedure

A *scientific (causal) model* describe the causal assumptions and mechanisms underlying a system, and facilitate inferences about causal relationships from data [@Hitchcock_2023].

To aid in the translation and visualization of the assumption underlying the DCJ procedure, Directed Acyclic Graphs (DAG) and Structural Causal Models (SCM) [@Pearl_2009; @Pearl_et_al_2016; @Cinelli_et_al_2021] are employed.


## References {.unnumbered}

:::{#refs}

:::